spring:
  datasource:
    url: jdbc:postgresql://smarthouse-db:5432/smarthouse

logging:
  filepath: /var/log/smarthouse
  level:
    org:
      hibernate:
        SQL: warn

mqtt:
  server-in: smarthouse-mqtt-broker
  server-out: smarthouse-mqtt-broker
  msgSavingEnabled: true
  msgSendingEnabled: true

influxdb:
  url: http://smarthouse-influxdb:8086

smarthouse:
  db:
    hostname: smarthouse-db
    port: 5432
    dump-on-destroy: false
    restore-on-startup: false
