apiVersion: v1
kind: ConfigMap
metadata:
  name: smarthouse-config
  namespace: smarthouse
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://smarthouse-db:5432/smarthouse"
  SPRING_DATASOURCE_USERNAME: "smarthouse"
