apiVersion: v1
kind: Service
metadata:
  name: smarthouse-controller
  namespace: smarthouse
  labels:
    app: smarthouse-controller
spec:
  selector:
    app: smarthouse-controller
  ports:
    - port: 24867
      targetPort: 24867
